# Localization node
dvl_max_velocity: 0.5

# [x y z roll pitch yaw]
imu_pose: [0, 0, 0, deg(-90), 0, 0]  

# keyframe spacing for the dead reckoning system
keyframe_duration: 1.0
keyframe_translation: 0.5
keyframe_rotation: deg(15)

# should we use the FOG? Do not set to true if there is no FOG sensor. 
use_gyro: True

# which IMU driver are we using 1 is the heavy and 2 is heavy MKII
# sample_data file is version 1 # 1 for sim, 2 for field
imu_version: 2
